### ISSUE TITLE
Failed read mapping datetime with timezone in postgresql

### ISSUE THREAD

**Issue by ibnbay99** [nils-braun/dask-sql#102]
Descriptions:
- When I want to connect/register table from postresql into dask-sql catalog (which successful register), but when I want to query that data got this error message
`NotImplementedError: The python type datetime64[ns, UTC] is not implemented (yet)` from this function `/dask_sql/mappings.py", line 78, in python_to_sql_type`

Reproduction Step Error:
- `from dask_sql import Context`
- `c = Context()`
- `import dask.dataframe as ddf`
- `user_df = ddf.read_sql_table(table="auth_user", schema="public", uri="postgresql://username:password@localhost:5432/dbname",index_col='id')`
- `c.create_table("pg.public.auth_user", user_df)`
- `c.sql("SELECT * FROM pg.public.auth_user")`

Notes:
I'm using this packages:
- psycopg2-binary      2.8.6
- dask                 2.30.0
- dask-sql             0.2.2 (I thing because this pypi release version is left behind?)
- distributed          2.30.0
- sqlalchemy 1.3.22

**Comment by nils-braun** [comment]
Hi @ibnbay99!
Thanks for using dask-sql and thanks for the bug report!
I assume your table looks similar to this one (in short):
```sql
CREATE TABLE auth_user (id INTEGER, date TIMESTAMP WITH TIME ZONE)
```
At least with this, I can reproduce your problem (one comment: table names in dask-sql should have not "." in them. I should probably mention this in the documentation and in the code - sorry for this).

With the referenced PR I am able to read from this table now. If you have a chance, would you like to also test it on your data?

**Comment by ibnbay99** [comment]
For table name I will change '.' into  '__', thanks @nils-braun.

Sorry if my question will out of context:
- If I create table it `must` from dask/pandas dataframe like for `DB SQL` right.
   When I query `not add option cache` `dask-sql` will be create a connection to `DB SQL` or just use `object` dask/pandas dataframe?
