### ISSUE TITLE
Error: Unable to instantiate java compiler

### ISSUE THREAD

**Issue by LaurentEsingle** [nils-braun/dask-sql#141]
Hi! @nils-braun,

As you already know I mistakenly opened this issue on Dask-Docker repo and you were kindly alerted by @jrbourbeau

I will copy/paste my original post here as well as your initial answer (Thank you for your quick reply)

Here is my original post:

####################################################################

**What happened**:

After installing Java and dask-sql using pip, whenever I try to run a SQL query from my python code I get the following error:
```
...
File "/home/vquery/.local/lib/python3.8/site-packages/dask_sql/context.py", line 378, in sql
    rel, select_names, _ = self._get_ral(sql)
  File "/home/vquery/.local/lib/python3.8/site-packages/dask_sql/context.py", line 515, in _get_ral
    nonOptimizedRelNode = generator.getRelationalAlgebra(validatedSqlNode)
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: Unable to instantiate java compiler
...
...
File "JaninoRelMetadataProvider.java", line 426, in org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile
  File "CompilerFactoryFactory.java", line 61, in org.codehaus.commons.compiler.CompilerFactoryFactory.getDefaultCompilerFactory
java.lang.java.lang.NullPointerException: java.lang.NullPointerException
```

**What you expected to happen**:

I should get a dataframe as a result.

**Minimal Complete Verifiable Example**:

```python

# The cluster/client setup is done first, in another module not the one executing the SQL query
# Also tried other cluster/scheduler types with the same error
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(
    n_workers=4,
    threads_per_worker=1,
    processes=False,
    dashboard_address=':8787',
    asynchronous=False,
    memory_limit='1GB'
    )
client = Client(cluster)

# The SQL code is executed in its own module
import dask.dataframe as dd
from dask_sql import Context

c = Context()
df = dd.read_parquet('/vQuery/files/results/US_Accidents_June20.parquet') 
c.register_dask_table(df, 'df')
df = c.sql("""select ID, Source from df""") # This line fails with the error reported

```

**Anything else we need to know?**:

As mentioned in the code snippet above, due to the way my application is designed, the Dask client/cluster setup is done before dask-sql context is created.

**Environment**:

- Dask version:
  - dask: 2020.12.0
  - dask-sql: 0.3.1
- Python version:
  - Python 3.8.5
- Operating System:
  - Ubuntu 20.04.1 LTS
- Install method (conda, pip, source):
  - pip
- Application Framework
  - Jupyter Notebook/Ipywidgets & Voila Server
 
**Install steps**

```
$ sudo apt install default-jre

$ sudo apt install default-jdk

$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

$ javac -version
javac 11.0.10

$ echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-amd64

$ pip install dask-sql

$ pip list | grep dask-sql
dask-sql               0.3.1
  ```

**Comment by LaurentEsingle** [comment]
Here is your initial answsr:

####################################################################

> Thanks @jrbourbeau for the mention.
> 
> Hi @LaurentEsingle and thank you very much for (1) using and testing dask-sql and (2) writing this very nice bug report!
> 
> As you opened this issue in the dask-docker repository I assume you are using the dask docker image? If yes, is there a reason you are not using the conda-installable dask-sql package or the dask-sql docker image (that question is more for me to understand :-))
> 
> I tried to reproduce your problem both inside the dask docker image and on my local computer (which also runs Ubuntu 20.04), but I was not able to see this error (I tried both with java 11.0.10 and 11.0.9). To be fair: I only checked with a CSV, not a parquet file but I do not see any reason that should be the problem :-)
> 
> Looking into some [old mail by Julian](http://mail-archives.apache.org/mod_mbox/calcite-dev/201611.mbox/%3C0F2BEE15-9F04-43EE-B78C-00EFE287C3E4@apache.org%3E), the core developer of Apache Calcite (which dask-sql uses), I think you are running into a similar problem: do you have some other java libraries in your classpath? Libraries like janino or codehaus? Do you set a custom classpath?
> 
> We can try some basic debugging. If you want, start your python interpreter and call
> 
> ```python
> from dask_sql import java
> # print where it gets the class from. That should be the DaskSQL.jar
> print(java.org.codehaus.commons.compiler.CompilerFactoryFactory.class_.getProtectionDomain().getCodeSource().getLocation())
> # print the JVM path, that should be your java installation
> print(java.jvmpath)
> # and now try to replicate the error
> java.org.codehaus.commons.compiler.CompilerFactoryFactory.getDefaultCompilerFactory()
> ```
> 
> Do those printed paths correspond to what you expect? Is the last line also failing?
> 
> Some possible solutions you might want to try out (depending on your use case):
> 
> * use conda for installation (the conda package of dask-sql ships with a "clean" java installation without dependency problems)
> * use the dask-sql docker image (nbraun/dask-sql) if that is an alternative
> * check with `$JAVA_HOME/bin/jps` and then `$JAVA_HOME/bin/jinfo` if the classpath is actually picked up correctly after just having imported dask_sql in a python shell (the first command will print all running JVMs and the second can be used to show additional information to a JVM)
> 
> Last but not least a question: as you mentioned you are creating a dask cluster before importing dask-sql (which is totally fine): did you test without any created dask cluster (it shouldn't make a difference, but you never know...)?

**Comment by LaurentEsingle** [comment]
Regarding the other options:
  - Use Conda: It is not advisable for me to do so as I use PIP for everything and throwing Conda in the mix after setting up the environment with PIP might not be such a good idea.
  - Dask-Sql container: my setup does not allow me to use an additional container for that purpose. The application already runs on a container and I want Dask-SQL feature to be seamlessly integrated in the application
  - Creating the context first. Doable but I cannot keep that configuration due to the application design. I tried in a test file but I still got the error

I will try in a Notebook (without Voila) and to check if Voila is the issue.

**Comment by nils-braun** [comment]
Hi @LaurentEsingle - that is really strange. All the output you send me looks quite reasonable (the fact that `user.dir` is different is fine - or are there any other files in your `/resources/vQuery/files` folder?). I am a bit out of ideas here :-/ Did you have a chance to check without Voila?

Is there a possibility that I can have a look into your code and do some tests by myself?

**Comment by LaurentEsingle** [comment]
Hi @nils-braun ,

I found the issue in my code thanks to your mention of  ```Thread.currentThread().getContextClassLoader()``` in your last comment.

It turns out it is a threading issue.  

My calls to Dask (and Dask-Sql) are done in a new thread. The problem is solved when making the calls without spawning a new thread.

That said it is not ideal for me as I do not want to block the UI and cannot use Dask Futures since I am using a Local scheduler most of the time. But at least I am able to make it work.

Thank you very much for your help.

Shall I close the issue now or do you need more information?

**Comment by nils-braun** [comment]
Thanks for the update!
That is quite interesting information, thanks for digging so deep! I never tried with a thread so far.

> Shall I close the issue now or do you need more information?

Well, I think we (or you) have the problem but so far there is no solution to make it work for you. 

To not block the UI makes a lot of sense! Have you thought about using a "single-machine distributed scheduler"? The setup is as easy as just using a local scheduler (see e.g. [here](https://docs.dask.org/en/latest/setup/single-distributed.html)) but does give you the benefits of using futures etc. You could e.g. spin up a distributed cluster with just a single local worker, which is more or less the same thing as you are currently doing (spinning up a new thread for each computation). You would then do the SQL parsing in the UI thread (but that should be really quick) and let the distributed worker do the rest. You can even choose between threads or processes in the distributed cluster.

**Comment by LaurentEsingle** [comment]
@nils-braun 

Indeed the next logical step for me should be to try the "single-machine distributed scheduler" to enable Dask Futures as you suggested.

Unfortunately I still get the "Unable to instantiate java compiler" error when using Futures.

The reason I think is because behind the scenes Futures use ```ThreadPoolExecutor, ProcessPoolExecutor```, etc. from python ```concurrent.futures library```.

Are you getting the same error when using threads in your testing environment?

Can you have a look at the following link  :    

[unable to find org.codehaus.commons.compiler.properties in java 11](https://github.com/janino-compiler/janino/issues/141)

Some workarounds are currently being suggested. Are they applicable to your project? What do you think? 

Thanx

**Comment by nils-braun** [comment]
> Unfortunately I still get the "Unable to instantiate java compiler" error when using Futures.

Maybe I misunderstood your use case then. Let me try to write what I understood and you can tell me, how wrong I was :-)
(but also see below for a possible solution without the futures using the SQL server and even more below with using your original proposal)

I imagine you have some sort of "frontend"/UI, where users can click a button or create some other type of input. In your original idea (which was quite reasonable, except the Java problem), you then spin up a new thread to kick of the computation with dask-sql, which then triggers a Dask computation with a `LocalScheduler`.
Now (that is what I understood), with the `futures` you should be able to live without this thread. If a user enters some input you kick off the dask-sql computation directly from within your UI process. This will basically only send the computation to the (local) cluster. This cluster does not run dask-sql, but only Dask - so you should not face the same problems as before.

While writing this, it came to my mind that - depending on your use case - you might also be interested in using dask-sql in [server mode](https://dask-sql.readthedocs.io/en/latest/pages/server.html). If you are only interested in sending SQL strings to dask-sql (if this is your use case), you might be able to do this with a usual `sqlalchemy` connection (which will work in a separate thread). You would then run the dask-sql server in a separate process (unrelated to your main process). 

> Are you getting the same error when using threads in your testing environment?

When using the "single-machine distributed scheduler" I do not get any errors (that is my usual development environment).

But, thanks for asking this question - as it might have brought us a bit closer to the solution.

Compare those two code blocks:
```python
import threading
import dask_sql


def run():
    c = dask_sql.Context()
    print(c.sql("SELECT 1 + 1").compute())

t = threading.Thread(target=run)
t.start()
t.join()
```

```python
import threading


def run():
    import dask_sql
    c = dask_sql.Context()
    print(c.sql("SELECT 1 + 1").compute())

t = threading.Thread(target=run)
t.start()
t.join()
```

The first one throws the error you described whereas the second one works. The reason is, that while importing `dask_sql`, the internal java virtual machine is spun up. If you now switch the thread, the JVM is accessed from a different thread, which probably confuses it. If you are able to only run dask-sql completely in the newly created thread, you would also be able to import it only after having created the thread - and this might already solve your issue (that is also new to me, so thanks for sharing your issue!)

> Can you have a look at the following link :

That is unfortunately not the same exception than we see here. Also, the code that raises the exception is in the Calcite library - not something I have directly access to (but I think with the solutions above, we might not even need to "fix" it).

**Comment by LaurentEsingle** [comment]
@nils-braun 

THANK YOU!

It works.

I was worried at firs about the overhead of importing dask-sql/spawning the JVM, setting the context and computing the results in a new thread each time a query is issued.

It turns out the overhead is minimal and not significant in my particular scenario (I am not expecting hundreds of users to connect to the application).

From a cold start (no previous queries), the timing is as follows in my system:
  - spawning the JVM:  about 1,5 seconds
  - getting the graph: about 2 seconds
  
On the second execution, the duration of each of the steps above is greatly reduced (a few microseconds)

Once the JVM is spawned, that same JVM is used for subsequent queries.

I think this usage of threads is worth mentioning in the documentation.

Again thank you!
