### ISSUE TITLE
Add a packaged version of dask-sql

### ISSUE THREAD

**Issue by nils-braun** [nils-braun/dask-sql#2]
Currently, `dask-sql` can only be installed via the source. We should find out, if uploading the packaged jar (contained in a wheel) together with the python code makes sense and if and how we can create a conda package (probably via conda-forge).

**Comment by mariusvniekerk** [comment]
conda-forge would gladly accept this

**Comment by nils-braun** [comment]
Thanks for the hint, that is very good to hear!
Once there is a somewhat ok-ish first version, I will upload to pipy and also create a conda-forge PR.

**Comment by nils-braun** [comment]
I have added a first release candidate for 0.1.0 on pipy (for testing) and have also created a conda recipe [here](https://github.com/conda-forge/staged-recipes/pull/12587)

**Comment by mrocklin** [comment]
I just had a play with this.  Fun!

I ran into tiny speed bumps, but they were expected at this stage.  In
general it was fun to play around.

**Comment by nils-braun** [comment]
Thanks for trying it out!
I already found one issue which causes some bad performance, which is the renaming of columns I do to be as general as possible at each stage. But this will be fixed soon.
If you have any particular test case you would like to share, I am super happy to have a look!

**Comment by kyprifog** [comment]
Btw I published my fork up to pypi here:  https://pypi.org/project/mason-dask-sql/   But I pinned and pushed up the JAR which is probbably not what you want to do.

Happy to help get the official verison out on pypi at some point.

**Comment by nils-braun** [comment]
I have seen your work @kyprifog ;-) Thanks for doing the first step here.
In my first draft I have also included the JAR in the wheel (see `setup.py` and the github workflows). I am not so sure if this is that bad. Because I definitely not want the user to need to install mvn just for this. I would assume that the cool thing about Java is, that it should actually be platform-independent :-) 
How would you suggest to do it better? Maybe I am just too naive here :-)

**Comment by kyprifog** [comment]
Actually personally I don't see any problem with packaging the jar either, I just assumed that you didn't want to do that based on the fact that it was in the gitignore.

I agree with not requiring the average pypi user with needing to install maven.   Probbably packaging the jar is the best route to go to be sensitive to that requirement.    The only issue I think is maybe with java compatability like the issue we stumbled on before here:  https://github.com/nils-braun/dask-sql/issues/23  but your adding various java versions to the github workflow will go a long way to solving that issue.

**Comment by nils-braun** [comment]
Good observation! Yes, I do not want to have it in the repo, therefore I put it in the .gitignore. Users downloading the project from github probably want to test things out by themselves (and are typically "developers") - and I do not think that jars in general should belong to a git repo (they are not very good to be shown in diffs...). Do you think that is inconsistent?

I also hope that testing it on windows and linux with two java versions will catch most if the incompatibilities - but what I do not test is building with one version and running with another. I always assume that this is the full strength of java, so I do not need to test it but maybe I should do exactly this. I need to find out if this can be done easily with GitHub actions.

**Comment by kyprifog** [comment]
Yeah I agree this is a good point.  Maybe a better place to put it is in a public s3 bucket, or something like artifactory.

**Comment by nils-braun** [comment]
> Yeah I agree this is a good point. Maybe a better place to put it is in a public s3 bucket, or something like artifactory. Since you are using .github maybe its worth seeing if you can do it with github package registry.

Just to make sure, I understand this correctly: you proposing to add the jar to an external provider so that developers do not need to build it by themselves or to not put it in the wheel? 
Because for me putting it into the wheel/conda package or uploading it to an additional external source will not be much of a difference (with the exception that putting it into the wheel will give the user a self-contained experience).
Giving developers the possibility to download it instead of rebuilding it is nice, but I am not sure if this is such a large burden (as it is automated with a `pip install -e .`). 
I guess I have misunderstood you in this point :-/

> You could do this with github actions (test cross versions) by actually just running the jar once from within the action as a post build step, alternating between various java versions. This along with the listed versions in the github workflows action would expand out the compatability matrix.

Yes! Will do this! Good suggestion.

**Comment by kyprifog** [comment]
Ah my bad I misunderstood, you are just wanting to push it up to the pypi package but not up in git.   Yeah this makes sense, you can just make sure that your publish script is pushing up the jar.   You will have to make sure that the jar is in the MANIFEST.in I believe.

**Comment by nils-braun** [comment]
I think after having created correct tests for different versions and having the pipy Package and the conda forge package ready and automatic I can close this issue.
