### ISSUE TITLE
Allow for multiple schemas

### ISSUE THREAD

**Issue by nils-braun** [nils-braun/dask-sql#203]
Currently, all tables, functions and other context variables are supposed to belong to the single schema "schema".
In principle, both `Calcite` and the SQL parser statements allows for multiple schemas, we would just need to implement:

- [ ] dictionaries instead of lists for functions, tables and models in the context
- [ ] passing the schema information on into the `RelationalAlgebraGenerator` object.
- [ ] statements for creating a schema, deleting it (with cascade) and switching the root schema (= the schema which is inherently used when no schema is defined).

**Comment by rajagurunath** [comment]
Hi @nils-braun ,

Need some more clarification on this issue, Please provide your view on this :

Currently we have following data structures/containers to store the meta information 

schema: str
functions: Dict[str, callable] 
table : Dict[str,DataContainer] 
models:  Dict[str, Tuple(sklearn_model,training_cols)]
experiments: Dict[str, pd.DataFrame]

To introduce multiple schema feature, what is your recommendation ?,(I have some difficulty, understanding first point mentioned above )

Are we planning some thing like using dict with key as schema name and list of dictionaries like below?

functions : Dict[str, List[Dict[str, callable]]] => {schema_name: [{fn_name: callable}]}
similarly for all other entities ? 

so that we can create , delete schema and their respective entities like functions, models, experiments?

**Comment by nils-braun** [comment]
Hi @rajagurunath 

yes, my first intention was to go from e.g. `tables: Dict[str, DataContainer]` to `Dict[str, Dict[str, DataContainer]`. However, as the number of items that we need to store for each schema grows (functions, table, models, experiments, ...) I am wondering if it would be better to just define a small helper data class 

```python
class SchemaData: # or a better name
    table: Dict[str, DataContainer] = {}
    ....
```

with some utility functions and then just store a dictionary of those `SchemaData` instances in the `context`. What do you think?

**Comment by rajagurunath** [comment]
Hi @nils-braun 

Thanks for the Hints & Explanation, completely agreed with your concern and tried implementing a small helper class in `dataContainer.py`, stored tables, functions, experiments, models inside `SchemaContainer`  based on your above explanation.

I modified all the files where we are  referencing tables,functions,experiments,models etc . here: https://github.com/nils-braun/dask-sql/compare/main...rajagurunath:feature/multiple_schema  for example like this - `context.schema[context.schema_name].tables[table_name]`, Need your help or suggestions here, is this the right way to access different entities using already set context.schema_name ? And how to get schema Names from calcite in places like create tables, models, experiments, etc. ( basically wherever we need)  Anything I am missing here?
 

And, Trying to add Create schema, drop Schema, use schema SQL statements :
Create Schema -- > Creates SchemaContainer object and stores it in schema Dict in the context
drop Schema  --> Removes the Schema from the Dict 
Use Schema  --> sets the current schema name in context.schema_name ( is this approach right, will it create any other problem/side effects  (like any race condition when sending subsequent requests to the server with two different schema_name )?)

**Comment by nils-braun** [comment]
Hi @rajagurunath 
Cool, I like having a class for that. I have never used the `singledispatchmethod` before - very cool idea. Not sure if it is really needed here, but cool to see anyways ;-)

I think you did already cover most of the changes, nice work! 

> And how to get schema Names from calcite in places like create tables, models, experiments, etc. 

I think we can be very pragmatic here: we only allow a user to edit (create/drop) entities in the currently selected schema. If a user wants to delete a table in a different schema, they will need to switch schemas. That is similar to e.g. a database in a SQL system. 
We could also replace all `SimpleIdentifiers` with `CompoundIdentifiers` in the parser definition, which would allow us to write things like `DROP TABLE foo.bar` to drop the table `bar` from the schema `foo` (even if it is not currently selected). Actually, `SELECT ... FROM table` does exactly this (and allows to select tables from different schemas in one select call). As a result, we can get the list of identifiers (instead of just a single identifier) with the `.names` member.

With that, the logic of something like `context.schema[context.schema_name].tables[table_name]` will get a bit more complicated (if the table name is compound, use the schema from the identifier, if not, use the currently active schema) - so I think it would be wise to get convenience functions for that to not repeat ourselves all the time. 

While writing this, I see that this is quite involved and I am not able to bring this into words reasonably well. How about the following: I will build up upon your branch and try to add the CompoundIdentifier I was talking of for `CREATE/DROP MODEL/VIEW/TABLE/EXPERIMENT` upon that (and hopefully learn how exactly it works while working on it). Is that ok for you? Am I allowed to add my changes to your very good first draft?

**Comment by rajagurunath** [comment]
Hi @nils-braun,

Thanks a lot for the detailed explanation, Now I understood the difference between `SimpleIdentifiers` with `CompoundIdentifiers`, Clearly I see your point, we need to have the convenience function.

It's all yours @nils-braun, 💟   I am just modifying the code here and there,  Please modify/change the code wherever you want, If you need any permission please let me, I am not sure what are all the permissions needed.

Actually, I understood some of the nuances from your detailed explanation But was not able to completely visualize/develop the convenience function. so please go ahead do your changes, I will take that as an example and try to finish the rest of the (multiple schemas) things.
