### ISSUE TITLE
Unrecognized option: --illegal-access=deny

### ISSUE THREAD

**Issue by kyprifog** [nils-braun/dask-sql#23]
Great work with this library!   I ran into one small snag:

dask-sql==0.1.dev13+gdf4572c
Unable to start JVM due to --illegal-access=deny.  Once I remove that option then the library seems to work fine

https://github.com/nils-braun/dask-sql/blob/main/dask_sql/java.py#L15

**Comment by nils-braun** [comment]
Thank for your bug report and thanks for trying out the package!
I assume that comes from a different java version.
Could you tell me yours via `java -version` and if you have installed java via conda?

The option prevents a warning in newer versions which will turn into a real exception in future versions.

**Comment by kyprifog** [comment]
```
java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

**Comment by nils-braun** [comment]
Thanks! I will create a PR to fix this

**Comment by kyprifog** [comment]
Thanks for your prompt attention!  I'll test this out later.
