### ISSUE TITLE
Unnamed Exprs in column names after aggregation

### ISSUE THREAD

**Issue by mrocklin** [nils-braun/dask-sql#27]
```python
import dask
import dask_sql
context = dask_sql.Context()
df = dask.datasets.timeseries()
context.register_dask_table(df, "timeseries")
context.sql("SELECT sum(x), sum(y) from timeseries").compute()
```

```
        EXPR$0      EXPR$1
0 -1072.053022  762.750336
```

**Comment by nils-braun** [comment]
That is a very reasonable suggestion.
Unfortunately, all that Apache Calcite gives to us is these `EXPR$` names. I think it would make sense to replace them "by hand" with the actual string in the SQL call (would be `sum(x)` in your case).

I guess what I could do is re-translate the parsed expression into SQL (which will hopefully turn the `LogicalProject(SUM, $0)` back into `sum(x)`).
