### ISSUE TITLE
Show better error messages

### ISSUE THREAD

**Issue by nils-braun** [nils-braun/dask-sql#4]
When there is a SQL validation error, the error is shown on the screen. However, we always get a nested Java and Python exception, which might lead to confusion.
The blazingSQL project created their own SQL exception in Java for this - we might also get along with just catching and parsing the Java exception in python and printing out a piece of more useful information to the user in the `Context.sql` function.

**Comment by mrocklin** [comment]
I ran into this myself.  Here was a small/simple example

```python
import dask
import dask_sql
context = dask_sql.Context()
df = dask.datasets.timeseries()
context.register_dask_table(df, "timeseries")
context.sql("SELECT * from timeseries where name=Tim")
```

As a user, nothing in the calcite stack trace means anything to me.  The error message itself is useful though.  I wouldn't mind chopping off everything in the cython/java side and just raising the exception without a meaningful traceback.  There is probably some value to devs in the traceback though I suppose.
