### ISSUE TITLE
Update dask docs yet?

### ISSUE THREAD

**Issue by martindurant** [nils-braun/dask-sql#46]
https://docs.dask.org/en/latest/dataframe-sql.html explicitly says that dask does not "implement" SQL. But now it does! This is a reminder to update that page, when this package feels ready enough to be publicised.

**Comment by raybellwaves** [comment]
Related to https://github.com/dask/dask/issues/6592

**Comment by raybellwaves** [comment]
PR in progress https://github.com/dask/dask/pull/7129

**Comment by nils-braun** [comment]
Thanks @raybellwaves for going forward here!
