### ISSUE TITLE
Unify the API of dask-sql and blazing-sql

### ISSUE THREAD

**Issue by nils-braun** [nils-braun/dask-sql#58]
After a very nice discussion with @felipeblazing (thanks again for reaching out!), we decided to unify the APIs of dask-sql and [blazing-sql](https://github.com/BlazingDB/blazingsql), so that users can switch between the different packages more easily (and therefore switch between "normal" CPU dask and GPU-enabled rapids). As blazing has been around much longer already, I think it would make sense to use blazings API as the target for dask-sql.

The entrypoint to all applications with dask-sql or blazing is to instantiate a context and then call methods on it.
blazing currently has the following methods on the context:

```
File System:
	.s3
	.localfs
	.hdfs
	.gs
	.show_filesystems

SQL:
	.explain
	.create_table
	.drop_table
	.sql
```

The SQL methods can be implemented quite quickly as they are basically already present (just with different names).
The FS methods are very interesting to have (see #28), so they definitely should come next. 
There is another method, `.log`, which however only makes sense in the blazing context and is very hard to port. 

Apart from the context API, there is of course also the very important question if the same SQL queries are understood. 
That should be handled next.

**Comment by felipeblazing** [comment]
This is so exciting for us!!!  The .log method is basically some hacky short hand that creates a table from the different log files that blazing generates and then allows you to query them. Since you are leveraging dask for all of the execution you shouldn't need to worry about .log at all. These are definitely the most important apis and if we both implemented them the same way should be easy to use our two engines interchangeably.

**Comment by mrocklin** [comment]
> After a very nice discussion with @felipeblazing (thanks again for reaching out!), we decided to unify the APIs of dask-sql and blazing-sql, so that users can switch between the different packages more easily

Just coming back from vacation and going through e-mails.  I was very happy to see this one in particular and thought I'd give a :heart:

**Comment by beckernick** [comment]
This is a *fantastic* idea and I also want to comment a heart ❤️  (copying @mrocklin 😄 )

**Comment by nils-braun** [comment]
With the latest PR, `dask-sql` now copies the blazing API in the important functions

	.explain
	.create_table
	.drop_table
	.sql

and is therefore interchangeable with it. It has no implementation of the filesystem methods - as they do not make a lot of sense when being only on the dask world (e.g. the S3 credential parameters can just be given when reading in the data itself) - which is different from the blazing usecase.

I think moving to the same API was a very large step forward for a better and simpler ecosystem and I am very happy we started this discussion!
