### ISSUE TITLE
Add documentation link to GitHub Repo

### ISSUE THREAD

**Issue by raybellwaves** [nils-braun/dask-sql#81]
Github allows you put a link to the documentation at the top of the page

Could put https://dask-sql.readthedocs.io/en/latest/ there

![image](https://user-images.githubusercontent.com/17162724/99292075-bbc78380-280e-11eb-827f-b38b364a8aa2.png)

**Comment by nils-braun** [comment]
Yes, makes a lot of sense!
I have done so :-)
