### ISSUE TITLE
Support Analyze Query

### ISSUE THREAD

**Issue by quasiben** [nils-braun/dask-sql#96]
This could very well be difficult to implement but the [ANALYZE](https://dev.mysql.com/doc/refman/5.6/en/analyze-table.html) query would be useful to have.  For reference this is what spark currently supports with respect to `ANALAYZE`:
https://spark.apache.org/docs/3.0.0/sql-ref-syntax-aux-analyze-table.html

**Comment by nils-braun** [comment]
Thanks for the feature request - depending on which part you refer that is either easy or not possible :-D Would you like to...
* get statistics on a table, e.g. as shown in this output table from the spark documentation:
```
DESC EXTENDED students name;
+--------------+----------+
|     info_name|info_value|
+--------------+----------+
|      col_name|      name|
|     data_type|    string|
|       comment|      NULL|
|           min|      NULL|
|           max|      NULL|
|     num_nulls|         0|
|distinct_count|         2|
|   avg_col_len|         4|
|   max_col_len|         4|
|     histogram|      NULL|
+--------------+----------+
```
* or would you like to have a more optimal query (computation) plan after having executed this statement?

**Comment by quasiben** [comment]
I should have been more clear, apologies.  The former, that is, getting statistics on tables is the feature request here

**Comment by nils-braun** [comment]
No no, that is absolutely fine. Both would have been a valid request! Fortunately, that one is easier ;-)
